# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# 

TEAM_ID = "5Z9R4HPE6N"
USERNAME = "cirnotoss@gmail.com"
APP_IDENTIFIER = "com.alekseykozin.showcase"

# 

platform :ios do
  desc "Description of what the lane does"
  lane :distribute do
    increment_build_number(build_number: number_of_commits)
    update_app_identifier(
      xcodeproj: "showcase.xcodeproj",
      plist_path: "showcase/Info.plist",
      app_identifier: APP_IDENTIFIER
    )
    register_devices(
      team_id: TEAM_ID,
      username: USERNAME,
      devices: {
        "Aleksey's iPhone 7" => "4c09eadc09b4d54f67586d8394ecc4624c25727d",
        "Marina's iPhone SE" => "7ee6cd91f4946af9936f272b636824c488b07962",
      },
    )
    match(
      type: "adhoc", 
      team_id: TEAM_ID,
      username: USERNAME,
      app_identifier: APP_IDENTIFIER,
      git_url: "git@github.com:aleksejkozin/private_keys_and_certificates.git",
      force: true
      )
    build_ios_app(
        workspace: "showcase.xcworkspace",
        scheme: "showcase",
        configuration: "Release",
        export_method: "ad-hoc",
    )
    firebase_app_distribution(
        app: "1:865456420308:ios:d9ad68afe874eb92329241",
        groups: "general",
        release_notes: "Lots of amazing new features to test out!",
    )
  end
end
